<?php
/*
	Author: Helge Sverre Hessevik Liseth
	Website: www.helgesverre.com
	
	Email: helge.sverre@gmail.com
	Twitter: @HelgeSverre
	
	License: Attribution-ShareAlike 4.0 International
	
*/


/**
 * Class responsible for checking if a domain is registered
 *
 * @author  Helge Sverre <email@helgesverre.com>
 *
 * @param boolean $error_reporting Set if the function should display errors or suppress them, default is false
 * @return boolean true means the domain is NOT registered
 */
class DomainAvailability {

	private  $error_reporting;


	public function __construct($debug = false) {
		if ( $debug ) {
			error_reporting(E_ALL);
			$error_reporting = true;
		} else {
			error_reporting(0);
			$error_reporting = false;
		}

	}


	/**
	 * This function checks if the supplied domain name is registered
	 *
	 * @author  Helge Sverre <email@helgesverre.com>
	 *
	 * @param string $domain The domain that will be checked for registration.
	 * @param boolean $error_reporting Set if the function should display errors or suppress them, default is TRUE
	 * @return boolean true means the domain is NOT registered
	 */
	public function is_available($domain) {

		// make the domain lowercase
		$domain = strtolower($domain);

		// Set the timeout (in seconds) for the socket open function.
		$timeout = 10;



		/**
		 * This array contains the list of WHOIS servers and the "domain not found" string
		 * to be searched for to check if the domain is available for registration.
		 *
		 * NOTE: The "domain not found" string may change at any time for any reason.
		 */
		$whois_arr = array(
			"abbott" => array("whois.afilias-srs.net","NOT FOUND"),
"ac.ac" => array("whois.nic.ac","is available for purchase"),
"ac.at" => array("whois.nic.at","nothing found"),
"ac.be" => array("whois.dns.be","No such domain"),
"ac.cn" => array("whois.cnnic.net.cn","no matching record"),
"ac.id" => array("whois.pandi.or.id","DOMAIN NOT FOUND"),
"ac.il" => array("whois.isoc.org.il","No data was found"),
"ac.in" => array("whois.inregistry.in","NOT FOUND"),
"ac.jp" => array("whois.nic.ad.jp","No match!!"),
"ac.ke" => array("whois.kenic.or.ke","No Object Found"),
"ac.kr" => array("whois.nic.or.kr","The requested domain was not found"),
"ac.nz" => array("whois.srs.net.nz","220 Available"),
"ac.th" => array("whois.thnic.net","No match for"),
"ac.tz" => array("whois.tznic.or.tz","No entries found"),
"ac.uk" => array("whois.ja.net","Sorry - no"),
"ac.za" => array("whois.co.za","No information available"),
"academy" => array("whois.donuts.co","Domain not found"),
"accountants" => array("whois.donuts.co","Domain not found"),
"accountant" => array("whois.nic.accountant","Not found"),
"active" => array("whois.afilias-srs.net","NOT FOUND"),
"actor" => array("whois.unitedtld.com","Domain not found."),
"ac" => array("whois.nic.ac","is available for purchase"),
"adm.br" => array("whois.nic.br","No match for"),
"ads" => array("whois.nic.google","Domain not found."),
"adult" => array("whois.afilias-srs.net","NOT FOUND"),
"adv.br" => array("whois.nic.br","No match for"),
"ad" => array("whois.ripe.net","no entries found"),
"aeg" => array("whois.nic.aeg","No match for"),
"aero" => array("whois.aero","NOT FOUND"),
"ae" => array("whois-check.aeda.net.ae","---Available"),
"ae" => array("whois.aeda.net.ae","Not Available"),
"afl" => array("whois.nic.afl","No Data Found"),
"af" => array("whois.nic.af","No Object Found"),
"agency" => array("whois.donuts.co","Domain not found"),
"agro.pl" => array("whois.dns.pl","No information available"),
"ag" => array("whois.nic.ag","NOT FOUND"),
"ah.cn" => array("whois.cnnic.net.cn","No matching record"),
"aid.pl" => array("whois.dns.pl","No information available"),
"airforce" => array("whois.unitedtld.com","Domain not found"),
"airtel" => array("whois.nic.airtel","No match for"),
"ai" => array("whois.ai","If you would like to register this"),
"allfinanz" => array("whois.ksregistry.net","The queried object does not exist"),
"alsace" => array("whois-alsace.nic.fr","Requested Domain cannot be found"),
"alt.za" => array("whois.co.za","No information available"),
"am.br" => array("whois.nic.br","No match for"),
"amsterdam" => array("whois.nic.amsterdam","Domain Status: free"),
"am" => array("whois.amnic.net","No match"),
"android" => array("whois.nic.google","Domain not found."),
"apartments" => array("whois.donuts.co","Domain not found"),
"app" => array("whois.nic.google","Domain not found."),
"aquarelle" => array("whois-aquarelle.nic.fr","Requested Domain cannot be found"),
"archi" => array("whois.ksregistry.net","The queried object does not exist"),
"army" => array("whois.rightside.co","Domain not found."),
"arpa" => array("whois.iana.org","0 objects"),
"arq.br" => array("whois.nic.br","No match for"),
"art.br" => array("whois.nic.br","No match for"),
"arts.ro" => array("whois.rotld.ro","No entries found"),
"asia" => array("whois.nic.asia","NOT FOUND"),
"asn.au" => array("whois.aunic.net","No Data Found"),
"asso.fr" => array("whois.nic.fr","No entries found"),
"asso.mc" => array("whois.ripe.net","no entries found"),
"associates" => array("whois.donuts.co","Domain not found"),
"as" => array("whois.nic.as","NOT FOUND"),
"atm.pl" => array("whois.dns.pl","No information available"),
"attorney" => array("whois.rightside.co","Domain not found"),
"at" => array("whois.nic.at","nothing found"),
"auction" => array("whois.unitedtld.com","Domain not found."),
"audio" => array("whois.uniregistry.net","is available for"),
"auto.pl" => array("whois.dns.pl","No information available"),
"autos" => array("whois.afilias-srs.net","BROKEN"),
"auto" => array("whois.uniregistry.net","is available for registration"),
"au" => array("whois.audns.net.au","No Data Found"),
"aw" => array("whois.nic.aw","is free"),
"ax" => array("whois.ax","No records matching"),
"band" => array("whois.rightside.co","Domain not found."),
"bank" => array("whois.nic.bank","No match for"),
"barcelona" => array("whois.nic.barcelona","no matching objects found"),
"barclaycard" => array("whois.nic.barclaycard","No Data Found"),
"barclays" => array("whois.nic.barclays","No Data Found"),
"bargains" => array("whois.donuts.co","Domain not found"),
"bar" => array("whois.nic.bar","DOMAIN NOT FOUND"),
"bauhaus" => array("whois.nic.bauhaus","no matching objects found"),
"bayern" => array("whois-dub.mm-registry.com","The queried object does not exist"),
"bbc" => array("whois.nic.bbc","This domain name has not been registered."),
"bbs.tr" => array("whois.metu.edu.tr","No match found"),
"bbva" => array("whois.nic.bbva","No match for"),
"bcn" => array("whois.nic.bcn","no matching objects found"),
"beer" => array("whois.nic.beer","queried object does not exist"),
"bentley" => array("whois.nic.bentley","This domain name has not been registered."),
"berlin" => array("whois.nic.berlin","No match"),
"best" => array("whois.nic.best","queried object does not exist"),
"bet" => array("whois.afilias.net","BROKEN"),
"be" => array("whois.dns.be","Status:	AVAILABLE"),
"bg" => array("whois.register.bg","does not exist in database"),
"bid" => array("whois.nic.bid","queried object does not exist"),
"bike" => array("whois.donuts.co","Domain not found"),
"bingo" => array("whois.donuts.co","Domain not found"),
"bio" => array("whois.ksregistry.net","The queried object does not exist"),
"biz.id" => array("whois.pandi.or.id","DOMAIN NOT FOUND"),
"biz.pl" => array("whois.dns.pl","No information available"),
"biz" => array("whois.nic.biz","Not found"),
"bi" => array("whois1.nic.bi","No Object Found"),
"bj.cn" => array("whois.cnnic.net.cn","No matching record"),
"bj" => array("whois.nic.bj","No Object Found"),
"blackfriday" => array("whois.uniregistry.net","is available"),
"black" => array("whois.afilias.net","NOT FOUND"),
"blue" => array("whois.nic.blue","NOT FOUND"),
"bmw" => array("whois.ksregistry.net","The queried object does not exist"),
"bnl" => array("whois.afilias-srs.net","BROKEN"),
"bnpparibas" => array("whois.afilias-srs.net","NOT FOUND"),
"bn" => array("whois.bnnic.bn","Domain Not Found"),
"boats" => array("whois.afilias-srs.net","BROKEN"),
"bond" => array("whois.nic.bond","No Data Found"),
"boo" => array("whois.nic.google","Domain not found."),
"boutique" => array("whois.donuts.co","Domain not found"),
"bo" => array("whois.nic.bo","BROKEN"),
"br.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"bradesco" => array("whois-cl01.mm-registry.com","Not Registered"),
"bridgestone" => array("whois.nic.bridgestone","No Data Found"),
"broker" => array("whois.nic.broker","No match for"),
"brother" => array("whois.nic.brother","No Data Found"),
"brussels" => array("whois.nic.brussels","No match"),
"brussels" => array("whois.nic.brussels","is still available"),
"br" => array("whois.nic.br","No match for"),
"budapest" => array("whois-dub.mm-registry.com","The queried object does not exist"),
"builders" => array("whois.donuts.co","Domain not found"),
"build" => array("whois.nic.build","No Data Found"),
"business" => array("whois.donuts.co","Domain not found"),
"buzz" => array("whois.nic.buzz","queried object does not exist"),
"bw" => array("whois.nic.net.bw","No Object Found"),
"by" => array("whois.cctld.by","Object does not exist"),
"bzh" => array("whois-bzh.nic.fr","Requested Domain cannot be found"),
"bz" => array("whois.afilias-grs.info.","NOT FOUND"),
"cab" => array("whois.donuts.co","Domain not found"),
"cafe" => array("whois.donuts.co","Domain not found"),
"cal" => array("whois.nic.google","Domain not found."),
"camera" => array("whois.donuts.co","Domain not found"),
"camp" => array("whois.donuts.co","Domain not found"),
"cancerresearch" => array("whois.nic.cancerresearch","No Data Found"),
"canon" => array("whois.nic.canon","DOMAIN NOT FOUND"),
"capetown" => array("capetown-whois.registry.net.za","Available"),
"capital" => array("whois.donuts.co","Domain not found"),
"cards" => array("whois.donuts.co","Domain not found"),
"careers" => array("whois.donuts.co","Domain not found"),
"career" => array("whois.nic.career","No match for"),
"care" => array("whois.donuts.co","Domain not found"),
"cars" => array("whois.uniregistry.net","is available for registration"),
"casa" => array("whois.nic.casa","queried object does not exist"),
"cash" => array("whois.donuts.co","Domain not found"),
"casino" => array("whois.donuts.co","Domain not found"),
"catering" => array("whois.donuts.co","Domain not found"),
"cat" => array("whois.cat","NOT FOUND"),
"ca" => array("whois.cira.ca","Domain status:         available"),
"cba" => array("whois.nic.cba","No Data Found"),
"cc" => array("whois.nic.cc","No match"),
"cd" => array("whois.cd","No match"),
"center" => array("whois.donuts.co","Domain not found"),
"ceo" => array("whois.nic.ceo","Not found"),
"cern" => array("whois.afilias-srs.net","NOT FOUND"),
"cfa" => array("whois.nic.cfa","No match for"),
"cfd" => array("whois.nic.cfd","No match for"),
"cf" => array("whois.dot.cf","Invalid query or domain name not known"),
"channel" => array("whois.nic.google","Domain not found."),
"chat" => array("whois.donuts.co","Domain not found"),
"cheap" => array("whois.donuts.co","Domain not found"),
"christmas" => array("whois.uniregistry.net","is available"),
"chrome" => array("whois.nic.google","Domain not found."),
"church" => array("whois.donuts.co","Domain not found"),
"ch" => array("whois.nic.ch","not have an entry"),
"city" => array("whois.donuts.co","Domain not found"),
"ci" => array("whois.nic.ci","not found"),
"claims" => array("whois.donuts.co","Domain not found"),
"cleaning" => array("whois.donuts.co","Domain not found"),
"click" => array("whois.nic.click","is available for registration"),
"clinic" => array("whois.donuts.co","Domain not found"),
"clothing" => array("whois.donuts.co","Domain not found"),
"cloud" => array("whois.nic.cloud","No Data Found"),
"club" => array("whois.nic.club","queried object does not exist"),
"cl" => array("whois.nic.cl","no existe"),
"cm" => array("whois.netcom.cm","Not Registered"),
"cn.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"cng.br" => array("whois.nic.br","No match for"),
"cnt.br" => array("whois.nic.br","No match for"),
"cn" => array("whois.cnnic.net.cn","No matching record"),
"co.ac" => array("whois.nic.ac","is available for purchase"),
"co.at" => array("whois.nic.at","nothing found"),
"co.id" => array("whois.pandi.or.id","DOMAIN NOT FOUND"),
"co.il" => array("whois.isoc.org.il","No data was found"),
"co.in" => array("whois.inregistry.in","NOT FOUND"),
"co.jp" => array("whois.nic.ad.jp","No match!!"),
"co.ke" => array("whois.kenic.or.ke","No Object Found"),
"co.ke" => array("whois.kenic.or.ke","Not Registered"),
"co.kr" => array("whois.nic.or.kr","is not registered"),
"co.nz" => array("whois.srs.net.nz","220 Available"),
"co.rs" => array("whois.rnids.rs","%ERROR:103"),
"co.th" => array("whois.thnic.net","No match for"),
"co.tz" => array("whois.tznic.or.tz","No entries found"),
"co.uk" => array("whois.nic.uk","No match"),
"co.ve" => array("whois.nic.ve","No match for"),
"co.za" => array("whois.registry.net.za","Available"),
"coach" => array("whois.donuts.co","Domain not found"),
"codes" => array("whois.donuts.co","Domain not found"),
"coffee" => array("whois.donuts.co","Domain not found"),
"college" => array("whois.nic.college","DOMAIN NOT FOUND"),
"cologne" => array("whois-fe1.pdt.cologne.tango.knipp.de","no matching objects found"),
"com.au" => array("whois.audns.net.au","No Data Found"),
"com.au" => array("whois.aunic.net","No Data Found"),
"com.br" => array("whois.nic.br","No match for"),
"com.cn" => array("whois.cnnic.net.cn","No matching record"),
"com.co" => array("whois.nic.co","Not found"),
"com.de" => array("whois.centralnic.com","Status: free"),
"com.ec" => array("whois.lac.net","No match found"),
"com.es" => array("whois.crsnic.net","No match for"),
"com.fr" => array("whois.nic.fr","No entries found"),
"com.gr" => array("http://grwhois.ics.forth.gr:800/plainwhois/plainWhois?domainName=","HTTPREQUEST-not exist"),
"com.gr" => array("http:\/\/grwhois.ics.forth.gr:800\/plainwhois\/plainWhois?domainName=","not exist"),
"com.gt" => array("http://www.gt/cgi-bin/whois.cgi?domain=","HTTPREQUEST-DOMINIO NO REGISTRADO"),
"com.gt" => array("http:\/\/www.gt\/cgi-bin\/whois.cgi?domain=","DOMINIO NO REGISTRADO"),
"com.hk" => array("whois.hkdnr.net.hk","The domain has not been registered"),
"com.mm" => array("whois.nic.mm","No domains matched"),
"com.mx" => array("whois.nic.mx","Object_Not_Found"),
"com.my" => array("whois.mynic.my","does not exist in database"),
"com.my" => array("whois.mynic.net.my","does not exist"),
"com.pa" => array("http://www.nic.pa/whois.php?nombre_d=","HTTPREQUEST-esta disponible para ser Registrado"),
"com.ph" => array("https://whois.dot.ph/?search=","HTTPREQUEST-Domain is available"),
"com.pl" => array("whois.dns.pl","No information available"),
"com.pt" => array("whois.dns.pt","no match"),
"com.ro" => array("whois.rotld.ro","No entries found"),
"com.ru" => array("whois.ripn.net","No entries found"),
"com.sg" => array("whois.nic.net.sg","Domain Not Found"),
"com.tr" => array("whois.metu.edu.tr","No match found"),
"com.tw" => array("whois.twnic.net","No Found"),
"com.ua" => array("whois.net.ua","No entries found"),
"com.ve" => array("whois.nic.ve","No match for"),
"commbank" => array("whois.nic.commbank","No Data Found"),
"community" => array("whois.donuts.co","Domain not found"),
"company" => array("whois.donuts.co","Domain not found"),
"computer" => array("whois.donuts.co","Domain not found"),
"com" => array("whois.crsnic.net","No match for"),
"condos" => array("whois.donuts.co","Domain not found"),
"construction" => array("whois.donuts.co","Domain not found"),
"consulting" => array("whois.unitedtld.com","Domain not found."),
"contractors" => array("whois.donuts.co","Domain not found"),
"cooking" => array("whois.nic.cooking","queried object does not exist"),
"cool" => array("whois.donuts.co","Domain not found"),
"coop" => array("whois.nic.coop","No domain records were found to match"),
"corsica" => array("whois-corsica.nic.fr","Requested Domain cannot be found"),
"country" => array("whois-dub.mm-registry.com","is available for registration"),
"coupons" => array("whois.donuts.co","Domain not found"),
"courses" => array("whois.aridnrs.net.au","No Data Found"),
"co" => array("whois.nic.co","Not found"),
"cq.cn" => array("whois.cnnic.net.cn","No matching record"),
"creditcard" => array("whois.donuts.co","Domain not found"),
"credit" => array("whois.donuts.co","Domain not found"),
"cricket" => array("whois.nic.cricket","The queried object does not exist"),
"cruises" => array("whois.donuts.co","Domain not found"),
"cr" => array("whois.nic.cr","No entries found."),
"cuisinella" => array("whois.nic.cuisinella","No Data Found"),
"cx" => array("whois.nic.cx","Domain Status: No Object Found"),
"cymru" => array("whois.nic.cymru","This domain name has not been registered."),
"cyou" => array("whois.afilias-srs.net","BROKEN"),
"cz" => array("whois.nic.cz","No entries found"),
"dabur" => array("whois.afilias-srs.net","BROKEN"),
"dad" => array("domain-registry-whois.l.google.com","Domain not found."),
"dad" => array("whois.nic.google","Domain not found."),
"dance" => array("whois.nic.dance","Domain not found."),
"date" => array("whois.nic.date","Not found"),
"dating" => array("whois.donuts.co","Domain not found"),
"datsun" => array("whois.nic.gmo","DOMAIN NOT FOUND"),
"day" => array("whois.nic.google","Domain not found."),
"dclk" => array("whois.nic.google","Domain not found."),
"deals" => array("whois.donuts.co","Domain not found"),
"degree" => array("whois.rightside.co","Domain not found."),
"delivery" => array("whois.donuts.co","Domain not found"),
"delta" => array("whois.afilias-srs.net","BROKEN"),
"democrat" => array("whois.nic.democrat","Domain not found."),
"dental" => array("whois.donuts.co","Domain not found"),
"dentist" => array("whois.rightside.co","Domain not found."),
"desa.id" => array("whois.pandi.or.id","DOMAIN NOT FOUND"),
"design" => array("whois.nic.design","DOMAIN NOT FOUND"),
"desi" => array("whois.nic.desi","queried object does not exist"),
"dev" => array("domain-registry-whois.l.google.com","Domain not found."),
"dev" => array("whois.nic.google","Domain not found."),
"de" => array("whois.denic.de","Status: free"),
"diamonds" => array("whois.donuts.co","Domain not found"),
"diet" => array("whois.uniregistry.net","is available for registration"),
"digital" => array("whois.donuts.co","Domain not found"),
"directory" => array("whois.donuts.co","Domain not found"),
"direct" => array("whois.donuts.co","Domain not found"),
"discount" => array("whois.donuts.co","Domain not found"),
"dk" => array("whois.dk-hostmaster.dk","No entries found"),
"dm" => array("whois.nic.dm","not found..."),
"dn.ua" => array("whois.net.ua","No entries found"),
"docs" => array("whois.nic.google","Domain not found."),
"dog" => array("whois.donuts.co","Domain not found"),
"doha" => array("whois.nic.doha","No Data Found"),
"domains" => array("whois.donuts.co","Domain not found"),
"doosan" => array("whois.nic.doosan","No match for"),
"download" => array("whois.nic.download","queried object does not exist"),
"drive" => array("whois.nic.google","Domain not found."),
"durban" => array("whois.nic.durban","Available"),
"dvag" => array("whois.ksregistry.net","The queried object does not exist"),
"dvag" => array("whois.ksregistry.net","not found..."),
"dz" => array("whois.nic.dz","NO OBJECT FOUND!"),
"eat" => array("domain-registry-whois.l.google.com","Domain not found."),
"eat" => array("whois.nic.google","Domain not found."),
"ecn.br" => array("whois.nic.br","No match for"),
"ec" => array("whois.nic.ec","Not Registered"),
"edu.au" => array("whois.aunic.net","No Data Found"),
"edu.cn" => array("whois.cnnic.net.cn","No matching record"),
"edu.es" => array("whois.crsnic.net","No match for"),
"edu.gr" => array("http://grwhois.ics.forth.gr:800/plainwhois/plainWhois?domainName=","HTTPREQUEST-not exist"),
"edu.gr" => array("http:\/\/grwhois.ics.forth.gr:800\/plainwhois\/plainWhois?domainName=","not exist"),
"edu.gt" => array("http://www.gt/cgi-bin/whois.cgi?domain=","HTTPREQUEST-DOMINIO NO REGISTRADO"),
"edu.gt" => array("http:\/\/www.gt\/cgi-bin\/whois.cgi?domain=","DOMINIO NO REGISTRADO"),
"edu.hk" => array("whois.hkdnr.net.hk","The domain has not been registered"),
"edu.mm" => array("whois.nic.mm","No domains matched"),
"edu.mx" => array("whois.nic.mx","Object_Not_Found"),
"edu.my" => array("whois.mynic.my","does not exist in database"),
"edu.my" => array("whois.mynic.net.my","does not exist"),
"edu.pl" => array("whois.dns.pl","No information available"),
"edu.pt" => array("whois.dns.pt","no match"),
"edu.rs" => array("whois.rnids.rs","%ERROR:103"),
"edu.sg" => array("whois.nic.net.sg","Domain Not Found"),
"edu.tr" => array("whois.metu.edu.tr","No match found"),
"edu.za" => array("whois.co.za","No information available"),
"education" => array("whois.donuts.co","Domain not found"),
"edu" => array("whois.internic.net","No match for"),
"ee" => array("whois.tld.ee","% No entries found."),
"ee" => array("whois.tld.ee","no entries found"),
"email" => array("whois.donuts.co","Domain not found"),
"emerck" => array("whois.afilias-srs.net","NOT FOUND"),
"energy" => array("whois.donuts.co","Domain not found"),
"eng.br" => array("whois.nic.br","No match for"),
"engineering" => array("whois.donuts.co","Domain not found"),
"engineer" => array("whois.nic.engineer","Domain not found"),
"enterprises" => array("whois.donuts.co","Domain not found"),
"epson" => array("whois.aridnrs.net.au","No Data Found"),
"equipment" => array("whois.donuts.co","Domain not found"),
"ernet.in" => array("whois.inregistry.in","NOT FOUND"),
"erni" => array("whois.nic.erni","no matching objects found"),
"esp.br" => array("whois.nic.br","No match for"),
"esq" => array("domain-registry-whois.l.google.com","Domain not found."),
"esq" => array("whois.nic.google","Domain not found."),
"estate" => array("whois.donuts.co","Domain not found"),
"es" => array("whois.nic.es","There is no information available on the domain consulted"),
"etc.br" => array("whois.nic.br","No match for"),
"eti.br" => array("whois.nic.br","No match for"),
"eu.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"eu.lv" => array("whois.biz","Not found"),
"eurovision" => array("whois.nic.eurovision","no matching objects found"),
"eus" => array("whois.eus.coreregistry.net","% no matching objects found"),
"eus" => array("whois.eus.coreregistry.net","no matching objects found"),
"eu" => array("whois.eu","Status: AVAILABLE"),
"exchange" => array("whois.donuts.co","Domain not found"),
"expert" => array("whois.donuts.co","Domain not found"),
"exposed" => array("whois.donuts.co","Domain not found"),
"express" => array("whois.donuts.co","Domain not found"),
"fail" => array("whois.donuts.co","Domain not found"),
"family" => array("whois.rightside.co","---Domain not found."),
"fans" => array("whois.nic.fans","DOMAIN NOT FOUND"),
"farm" => array("whois.donuts.co","Domain not found"),
"fashion" => array("whois-dub.mm-registry.com","is available for registration"),
"feedback" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"fin.ec" => array("whois.lac.net","No match found"),
"finance" => array("whois.donuts.co","Domain not found"),
"financial" => array("whois.donuts.co","Domain not found"),
"firm.ro" => array("whois.rotld.ro","No entries found"),
"firmdale" => array("whois.nic.firmdale","Domain Not Found"),
"fishing" => array("whois-dub.mm-registry.com","is available for registration"),
"fish" => array("whois.donuts.co","Domain not found"),
"fitness" => array("whois.donuts.co","Domain not found"),
"fit" => array("whois.nic.fit","queried object does not exist"),
"fi" => array("whois.ficora.fi","Domain not found"),
"flights" => array("whois.donuts.co","Domain not found"),
"florist" => array("whois.donuts.co","Domain not found"),
"flowers" => array("whois.uniregistry.net","is available for"),
"flsmidth" => array("whois.ksregistry.net","not found..."),
"fly" => array("domain-registry-whois.l.google.com","Domain not found."),
"fm.br" => array("whois.nic.br","No match for"),
"fm" => array("whois.nic.fm","Not Registered"),
"football" => array("whois.donuts.co","Domain not found"),
"foo" => array("domain-registry-whois.l.google.com","Domain not found."),
"forsale" => array("whois.unitedtld.com","Domain not found."),
"fot.br" => array("whois.nic.br","No match for"),
"foundation" => array("whois.donuts.co","Domain not found"),
"fo" => array("whois.nic.fo","no entries found"),
"frl" => array("whois.nic.frl","is still available"),
"frogans" => array("whois-frogans.nic.fr","Requested Domain cannot be found"),
"fr" => array("whois.nic.fr","No entries found"),
"fst.br" => array("whois.nic.br","No match for"),
"fund" => array("whois.donuts.co","Domain not found"),
"furniture" => array("whois.donuts.co","Domain not found"),
"futbol" => array("whois.nic.futbol","Domain not found."),
"futbol" => array("whois.unitedtld.com","Domain not found"),
"g12.br" => array("whois.nic.br","No match for"),
"gallery" => array("whois.donuts.co","Domain not found"),
"gal" => array("whois.gal.coreregistry.net","% no matching objects found"),
"garden" => array("whois.nic.garden","queried object does not exist"),
"gb.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"gb.net" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"gbiz" => array("domain-registry-whois.l.google.com","Domain not found."),
"gd.cn" => array("whois.cnnic.net.cn","No matching record"),
"gdn" => array("whois.gdnregistry.com","Domain Not Found"),
"gd" => array("whois.nic.gd","not found..."),
"geek.nz" => array("whois.srs.net.nz","220 Available"),
"gen.nz" => array("whois.srs.net.nz","220 Available"),
"gent" => array("whois.nic.gent","is still available"),
"gf" => array("whois.nplus.gf","not found in our database"),
"ggee" => array("whois.nic.ggee","DOMAIN NOT FOUND"),
"gg" => array("whois.gg","NOT FOUND"),
"gifts" => array("whois.donuts.co","Domain not found"),
"gift" => array("whois.uniregistry.net","is available for"),
"gives" => array("whois.rightside.co","Domain not found."),
"gi" => array("whois2.afilias-grs.net","NOT FOUND"),
"glass" => array("whois.donuts.co","Domain not found"),
"gle" => array("domain-registry-whois.l.google.com","Domain not found."),
"global" => array("whois.nic.global","NOT FOUND"),
"globo" => array("whois.gtlds.nic.br","No match for"),
"gl" => array("whois.nic.gl","Domain Status: No Object Found"),
"gmail" => array("domain-registry-whois.l.google.com","Domain not found."),
"gmina.pl" => array("whois.dns.pl","No information available"),
"gmx" => array("whois-fe1.gmx.tango.knipp.de","% no matching objects found"),
"go.id" => array("whois.idnic.net.id","Not found"),
"go.jp" => array("whois.nic.ad.jp","No match!!"),
"go.ke" => array("whois.kenic.or.ke","No Object Found"),
"go.kr" => array("whois.nic.or.kr","domain was not found"),
"go.kr" => array("whois.nic.or.kr","is not registered"),
"go.th" => array("whois.thnic.net","No match for"),
"go.tz" => array("whois.tznic.or.tz","No entries found"),
"gob.es" => array("whois.crsnic.net","No match for"),
"gob.gt" => array("http://www.gt/cgi-bin/whois.cgi?domain=","HTTPREQUEST-DOMINIO NO REGISTRADO"),
"gob.gt" => array("http:\/\/www.gt\/cgi-bin\/whois.cgi?domain=","DOMINIO NO REGISTRADO"),
"gob.mx" => array("whois.nic.mx","Object_Not_Found"),
"goldpoint" => array("whois.nic.goldpoint","DOMAIN NOT FOUND"),
"google" => array("domain-registry-whois.l.google.com","Domain not found."),
"goog" => array("domain-registry-whois.l.google.com","Domain not found."),
"goo" => array("whois.nic.gmo","DOMAIN NOT FOUND"),
"gop" => array("whois-cl01.mm-registry.com","is available for registration"),
"gov.br" => array("whois.nic.br","No match for"),
"gov.cn" => array("whois.cnnic.net.cn","No matching record"),
"gov.ec" => array("whois.lac.net","No match found"),
"gov.gr" => array("http://grwhois.ics.forth.gr:800/plainwhois/plainWhois?domainName=","HTTPREQUEST-not exist"),
"gov.gr" => array("http:\/\/grwhois.ics.forth.gr:800\/plainwhois\/plainWhois?domainName=","not exist"),
"gov.il" => array("whois.isoc.org.il","No data was found"),
"gov.in" => array("whois.inregistry.in","NOT FOUND"),
"gov.mm" => array("whois.nic.mm","No domains matched"),
"gov.mx" => array("whois.nic.mx","Object_Not_Found"),
"gov.my" => array("whois.mynic.my","does not exist in database"),
"gov.my" => array("whois.mynic.net.my","does not exist"),
"gov.sg" => array("whois.nic.net.sg","Domain Not Found"),
"gov.tr" => array("whois.metu.edu.tr","No match found"),
"gov.za" => array("whois.co.za","No information available"),
"gov" => array("whois.nic.gov","No match for"),
"gq" => array("whois.dominio.gq","Invalid query or domain name not known"),
"graphics" => array("whois.donuts.co","Domain not found"),
"gratis" => array("whois.donuts.co","Domain not found"),
"green" => array("whois.afilias.net","NOT FOUND"),
"gripe" => array("whois.donuts.co","Domain not found"),
"gr" => array("http://grwhois.ics.forth.gr:800/plainwhois/plainWhois?domainName=","HTTPREQUEST-not exist"),
"gs.cn" => array("whois.cnnic.net.cn","No matching record"),
"gsm.pl" => array("whois.dns.pl","No information available"),
"gs" => array("whois.nic.gs","No Object Found"),
"guide" => array("whois.donuts.co","Domain not found"),
"guitars" => array("whois.uniregistry.net","is available for"),
"guru" => array("whois.donuts.co","Domain not found"),
"gv.ac" => array("whois.nic.ac","Available"),
"gv.ac" => array("whois.nic.ac","is not registered"),
"gv.at" => array("whois.nic.at","nothing found"),
"gx.cn" => array("whois.cnnic.net.cn","No matching record"),
"gy" => array("whois.registry.gy","Domain Status: No Object Found"),
"gz.cn" => array("whois.cnnic.net.cn","No matching record"),
"hamburg" => array("whois.nic.hamburg","% No match"),
"hangout" => array("domain-registry-whois.l.google.com","Domain not found."),
"haus" => array("whois.unitedtld.com","Domain not found."),
"hb.cn" => array("whois.cnnic.net.cn","No matching record"),
"he.cn" => array("whois.cnnic.net.cn","No matching record"),
"healthcare" => array("whois.donuts.co","Domain not found"),
"help" => array("whois.nic.help","is available for registration"),
"here" => array("domain-registry-whois.l.google.com","Domain not found."),
"hi.cn" => array("whois.cnnic.net.cn","No matching record"),
"hiphop" => array("whois.uniregistry.net","is available for"),
"hiv" => array("whois.afilias-srs.net","NOT FOUND"),
"hk.cn" => array("whois.cnnic.net.cn","No matching record"),
"hk" => array("whois.hkirc.hk","The domain has not been registered"),
"hl.cn" => array("whois.cnnic.net.cn","No matching record"),
"hn.cn" => array("whois.cnnic.net.cn","No matching record"),
"hn" => array("whois.nic.hn","Domain Status: No Object Found"),
"holdings" => array("whois.donuts.co","Domain not found"),
"holiday" => array("whois.donuts.co","Domain not found"),
"horse" => array("whois-dub.mm-registry.com","is available for registration"),
"hosting" => array("whois.uniregistry.net","is available for"),
"host" => array("whois.nic.host","DOMAIN NOT FOUND"),
"house" => array("whois.donuts.co","Domain not found"),
"how" => array("domain-registry-whois.l.google.com","Domain not found."),
"hr" => array("whois.dns.hr","No entries found"),
"ht" => array("whois.nic.ht","Domain Status: No Object Found"),
"hu.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"hu" => array("whois.nic.hu","No match"),
"ibm" => array("whois.nic.ibm","No Data Found"),
"id.au" => array("whois.audns.net.au","No Data Found"),
"id.au" => array("whois.aunic.net","No Data Found"),
"idrett.no" => array("whois.norid.no","No match"),
"id" => array("whois.pandi.or.id","DOMAIN NOT FOUND"),
"ie" => array("whois.domainregistry.ie","% Not Registered"),
"ifm" => array("whois.nic.ifm","% no matching objects found"),
"il" => array("whois.isoc.org.il","No data was found"),
"immobilien" => array("whois.nic.immobilien","Domain not found."),
"immo" => array("whois.donuts.co","Domain not found"),
"im" => array("whois.nic.im","was not found"),
"in.rs" => array("whois.rnids.rs","%ERROR:103"),
"in.th" => array("whois.thnic.net","No match for"),
"ind.br" => array("whois.nic.br","No match for"),
"ind.gt" => array("http://www.gt/cgi-bin/whois.cgi?domain=","HTTPREQUEST-DOMINIO NO REGISTRADO"),
"ind.gt" => array("http:\/\/www.gt\/cgi-bin\/whois.cgi?domain=","DOMINIO NO REGISTRADO"),
"industries" => array("whois.donuts.co","Domain not found"),
"inf.br" => array("whois.nic.br","No match for"),
"infiniti" => array("whois.nic.gmo","DOMAIN NOT FOUND"),
"info.ke" => array("whois.kenic.or.ke","No Object Found"),
"info.pl" => array("whois.dns.pl","No information available"),
"info.ro" => array("whois.rotld.ro","No entries found"),
"info.ve" => array("whois.nic.ve","No match for"),
"info" => array("whois.afilias.net","NOT FOUND"),
"ing" => array("domain-registry-whois.l.google.com","Domain not found."),
"ink" => array("whois.donuts.co","Domain not found"),
"institute" => array("whois.donuts.co","Domain not found"),
"insure" => array("whois.donuts.co","Domain not found"),
"international" => array("whois.donuts.co","Domain not found"),
"int" => array("whois.iana.org","but this server does not have"),
"investments" => array("whois.donuts.co","Domain not found"),
"in" => array("whois.inregistry.in","NOT FOUND"),
"io" => array("whois.nic.io","is available"),
"iq" => array("whois.cmc.iq","Domain Status: No Object Found"),
"irish" => array("whois.afilias-srs.net","NOT FOUND"),
"ir" => array("whois.nic.ir","no entries found"),
"istanbul" => array("whois.nic.istanbul","NOT FOUND"),
"ist" => array("whois.nic.ist","NOT FOUND"),
"is" => array("whois.isnic.is","No entries found"),
"it" => array("whois.nic.it","AVAILABLE"),
"iwi.nz" => array("whois.srs.net.nz","220 Available"),
"java" => array("whois.nic.java","No match for"),
"jcb" => array("whois.nic.gmo","DOMAIN NOT FOUND"),
"jetzt" => array("whois.nic.jetzt","object does not exist"),
"je" => array("whois.je","NOT FOUND"),
"jl.cn" => array("whois.cnnic.net.cn","No matching record"),
"jobs" => array("whois.nic.jobs","No match for"),
"joburg" => array("whois.nic.joburg","Available"),
"jor.br" => array("whois.nic.br","No match for"),
"jp" => array("whois.jprs.jp","No match!!"),
"js.cn" => array("whois.cnnic.net.cn","No matching record"),
"juegos" => array("whois.uniregistry.net","is available for"),
"k12.il" => array("whois.isoc.org.il","No data was found"),
"k12.tr" => array("whois.metu.edu.tr","No match found"),
"kaufen" => array("whois.unitedtld.com","Domain not found."),
"kddi" => array("whois.nic.kddi","DOMAIN NOT FOUND"),
"ke" => array("whois.kenic.or.ke","Domain Status: No Object Found"),
"kg" => array("whois.domain.kg","is available for registration"),
"kh.ua" => array("whois.net.ua","No entries found"),
"kiev.ua" => array("whois.net.ua","No entries found"),
"kim" => array("whois.afilias.net","NOT FOUND"),
"kim" => array("whois.donuts.co","Domain not found"),
"kitchen" => array("whois.donuts.co","Domain not found"),
"kiwi.nz" => array("whois.srs.net.nz","220 Available"),
"kiwi" => array("whois.nic.kiwi","is available for registration"),
"ki" => array("whois.nic.ki","Domain Status: No Object Found"),
"koeln" => array("whois-fe1.pdt.koeln.tango.knipp.de","% no matching objects found"),
"krd" => array("whois.aridnrs.net.au","No Data Found"),
"kr" => array("whois.kr","is not registered"),
"kyoto" => array("whois.nic.kyoto","DOMAIN NOT FOUND"),
"ky" => array("whois.kyregistry.ky","is available for"),
"kz" => array("whois.nic.kz","Nothing found for this query."),
"lacaixa" => array("whois.nic.lacaixa","% no matching objects found"),
"land" => array("whois.donuts.co","Domain not found"),
"latrobe" => array("whois.nic.latrobe","No Data Found"),
"lat" => array("whois.nic.lat","Object_Not_Found"),
"lawyer" => array("whois.rightside.co","Domain not found."),
"la" => array("whois.nic.la","NOT FOUND"),
"lc" => array("whois2.afilias-grs.net","NOT FOUND"),
"lease" => array("whois.donuts.co","Domain not found"),
"leclerc" => array("whois-leclerc.nic.fr","Requested Domain cannot be found"),
"legal" => array("whois.donuts.co","Domain not found"),
"lel.br" => array("whois.nic.br","No match for"),
"lg.ua" => array("whois.net.ua","No entries found"),
"lgbt" => array("whois.afilias.net","NOT FOUND"),
"life" => array("whois.donuts.co","Domain not found"),
"lighting" => array("whois.donuts.co","Domain not found"),
"limited" => array("whois.donuts.co","Domain not found"),
"limo" => array("whois.donuts.co","Domain not found"),
"link" => array("whois.uniregistry.net","is available for"),
"live" => array("whois.rightside.co","---Domain not found."),
"li" => array("whois.nic.li","do not have an entry in our database matching your query"),
"ln.cn" => array("whois.cnnic.net.cn","No matching record"),
"loans" => array("whois.donuts.co","Domain not found"),
"lol" => array("whois.nic.lol","is available for registration"),
"london" => array("whois-lon.mm-registry.com","is available for registration"),
"lotte" => array("whois.nic.lotte","DOMAIN NOT FOUND"),
"love" => array("whois.nic.love","---DOMAIN NOT FOUND"),
"ltd.uk" => array("whois.nic.uk","No match"),
"ltda" => array("whois.afilias-srs.net","NOT FOUND"),
"lt" => array("whois.domreg.lt","Status:			available"),
"luxe" => array("whois-dub.mm-registry.com","is available for registration"),
"luxury" => array("whois.nic.luxury","No Data Found"),
"lu" => array("whois.dns.lu","No such domain"),
"lviv.ua" => array("whois.net.ua","No entries found"),
"ly" => array("whois.nic.ly","Not found"),
"madrid" => array("whois.madrid.rs.corenic.net","% no matching objects found"),
"mail.pl" => array("whois.dns.pl","No information available"),
"maison" => array("whois.donuts.co","Domain not found"),
"management" => array("whois.donuts.co","Domain not found"),
"mango" => array("whois.mango.coreregistry.net","% no matching objects found"),
"maori.nz" => array("whois.srs.net.nz","220 Available"),
"marketing" => array("whois.donuts.co","Domain not found"),
"market" => array("whois.rightside.co","Domain not found."),
"ma" => array("whois.iam.net.ma","Domain Status: No Object Found"),
"md" => array("whois.nic.md","No match for"),
"me.ke" => array("whois.kenic.or.ke","No Object Found"),
"me.tz" => array("whois.tznic.or.tz","No entries found"),
"me.uk" => array("whois.nic.uk","No match"),
"med.br" => array("whois.nic.br","No match for"),
"med.ec" => array("whois.lac.net","No match found"),
"media.pl" => array("whois.dns.pl","No information available"),
"media" => array("whois.donuts.co","Domain not found"),
"meet" => array("whois.afilias.net","NOT FOUND"),
"melbourne" => array("whois.aridnrs.net.au","No Data Found"),
"meme" => array("domain-registry-whois.l.google.com","Domain not found."),
"memorial" => array("whois.donuts.co","Domain not found"),
"menu" => array("whois.nic.menu","No Data Found"),
"men" => array("whois.nic.men","---No Data Found"),
"me" => array("whois.nic.me","NOT FOUND"),
"mi.th" => array("whois.thnic.net","No match for"),
"miami" => array("whois-dub.mm-registry.com","is available for registration"),
"miasta.pl" => array("whois.dns.pl","No information available"),
"mil.br" => array("whois.nic.br","No match for"),
"mil.ec" => array("whois.lac.net","No match found"),
"mil.gt" => array("http://www.gt/cgi-bin/whois.cgi?domain=","HTTPREQUEST-DOMINIO NO REGISTRADO"),
"mil.gt" => array("http:\/\/www.gt\/cgi-bin\/whois.cgi?domain=","DOMINIO NO REGISTRADO"),
"mil.id" => array("whois.idnic.net.id","Not found"),
"mil.pl" => array("whois.dns.pl","No information available"),
"mil.tr" => array("whois.metu.edu.tr","No match found"),
"mil.za" => array("whois.co.za","No information available"),
"mil" => array("whois.internic.net","No match for"),
"mini" => array("whois.ksregistry.net","not found..."),
"mk" => array("whois.marnet.mk","% No entries found."),
"ml" => array("whois.dot.ml","Invalid query or domain name not known"),
"mn" => array("whois.afilias-grs.info","NOT FOUND"),
"mo.cn" => array("whois.cnnic.net.cn","No matching record"),
"mobi.ke" => array("whois.kenic.or.ke","No Object Found"),
"mobi" => array("whois.dotmobiregistry.net","NOT FOUND"),
"moda" => array("whois.nic.moda","Domain not found"),
"monash" => array("whois.nic.monash","No Data Found"),
"money" => array("whois.donuts.co","Domain not found"),
"mortgage" => array("whois.rightside.co","Domain not found."),
"moscow" => array("whois.nic.moscow","No entries found"),
"mov" => array("domain-registry-whois.l.google.com","Domain not found."),
"mo" => array("whois.monic.mo","No match for"),
"msk.ru" => array("whois.nic.ru","No entries found"),
"ms" => array("whois.nic.ms","No Object Found"),
"mtpc" => array("whois.nic.gmo","DOMAIN NOT FOUND"),
"muni.il" => array("whois.isoc.org.il","No data was found"),
"museum" => array("whois.museum","NOT FOUND"),
"mu" => array("whois.nic.mu","Domain Status: No Object Found"),
"mx" => array("whois.nic.mx","No_Se_Encontro_El_Objeto/Object_Not_Found"),
"mx" => array("whois.nic.mx","Object_Not_Found"),
"my.id" => array("whois.pandi.or.id","DOMAIN NOT FOUND"),
"my" => array("whois.mynic.my","does not exist in database"),
"mz" => array("whois.nic.mz","Domain Status: No Object Found"),
"name" => array("whois.nic.name","No match"),
"navy" => array("whois.rightside.co","Domain not found."),
"na" => array("whois.na-nic.com.na","Domain Status: No Object Found"),
"nc" => array("whois.nc","No entries found"),
"ne.jp" => array("whois.nic.ad.jp","No match!!"),
"ne.ke" => array("whois.kenic.or.ke","No Object Found"),
"ne.kr" => array("whois.nic.or.kr","domain was not found"),
"ne.kr" => array("whois.nic.or.kr","is not registered"),
"ne.tz" => array("whois.tznic.or.tz","No entries found"),
"net.au" => array("whois-check.ausregistry.net.au","---Available"),
"net.au" => array("whois.aunic.net","No Data Found"),
"net.br" => array("whois.nic.br","No match for"),
"net.cn" => array("whois.cnnic.net.cn","No matching record"),
"net.co" => array("whois.nic.co","Not found"),
"net.ec" => array("whois.lac.net","No match found"),
"net.gr" => array("http://grwhois.ics.forth.gr:800/plainwhois/plainWhois?domainName=","HTTPREQUEST-not exist"),
"net.gr" => array("http:\/\/grwhois.ics.forth.gr:800\/plainwhois\/plainWhois?domainName=","not exist"),
"net.gt" => array("http://www.gt/cgi-bin/whois.cgi?domain=","HTTPREQUEST-DOMINIO NO REGISTRADO"),
"net.gt" => array("http:\/\/www.gt\/cgi-bin\/whois.cgi?domain=","DOMINIO NO REGISTRADO"),
"net.hk" => array("whois.hkdnr.net.hk","The domain has not been registered"),
"net.il" => array("whois.isoc.org.il","No data was found"),
"net.in" => array("whois.inregistry.in","NOT FOUND"),
"net.mm" => array("whois.nic.mm","No domains matched"),
"net.mx" => array("whois.nic.mx","Object_Not_Found"),
"net.my" => array("whois.mynic.net.my","does not exist"),
"net.nz" => array("whois.srs.net.nz","220 Available"),
"net.pa" => array("http://www.nic.pa/whois.php?nombre_d=","HTTPREQUEST-esta disponible para ser Registrado"),
"net.ph" => array("https://whois.dot.ph/?search=","HTTPREQUEST-Domain is available"),
"net.pl" => array("whois.dns.pl","No information available"),
"net.ru" => array("whois.ripn.net","No entries found"),
"net.sg" => array("whois.nic.net.sg","Domain Not Found"),
"net.th" => array("whois.thnic.net","No match for"),
"net.tr" => array("whois.metu.edu.tr","No match found"),
"net.tw" => array("whois.twnic.net","No Found"),
"net.ua" => array("whois.net.ua","No entries found"),
"net.uk" => array("whois.nic.uk","No match"),
"net.ve" => array("whois.nic.ve","No match for"),
"net.za" => array("net-whois.registry.net.za","Available"),
"network" => array("whois.donuts.co","Domain not found"),
"net" => array("whois.crsnic.net","No match for"),
"news" => array("whois.rightside.co","---Domain not found."),
"new" => array("domain-registry-whois.l.google.com","Domain not found."),
"nexus" => array("domain-registry-whois.l.google.com","Domain not found."),
"nf" => array("whois.nic.nf","Domain Status: No Object Found"),
"ngo.ph" => array("http://www2.dot.ph/WhoIs.asp?Domain=","HTTPREQUEST-is still available"),
"ngo.ph" => array("http:\/\/www2.dot.ph\/WhoIs.asp?Domain=","is still available"),
"ngo.za" => array("whois.co.za","No information available"),
"ngo" => array("whois.publicinterestregistry.net","NOT FOUND"),
"ng" => array("whois.nic.net.ng","Domain Status: No Object Found"),
"nico" => array("whois.nic.nico","DOMAIN NOT FOUND"),
"ninja" => array("whois.nic.ninja","Domain not found"),
"nissan" => array("whois.nic.gmo","DOMAIN NOT FOUND"),
"nl" => array("whois.domain-registry.nl","is free"),
"nm.cn" => array("whois.cnnic.net.cn","No matching record"),
"nm.kr" => array("whois.nic.or.kr","domain was not found"),
"nm.kr" => array("whois.nic.or.kr","is not registered"),
"no.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"nom.br" => array("whois.nic.br","No match for"),
"nom.co" => array("whois.nic.co","Not found"),
"nom.es" => array("whois.crsnic.net","No match for"),
"nom.pl" => array("whois.dns.pl","No information available"),
"nom.ro" => array("whois.rotld.ro","No entries found"),
"nom.za" => array("whois.co.za","No information available"),
"no" => array("whois.norid.no","No match"),
"nra" => array("whois.afilias-srs.net","NOT FOUND"),
"nrw" => array("whois.nic.nrw","The queried object does not exist: no matching objects found"),
"nt.ro" => array("whois.rotld.ro","No entries found"),
"ntr.br" => array("whois.nic.br","No match for"),
"nu" => array("whois.nic.nu","not found"),
"nx.cn" => array("whois.cnnic.net.cn","No matching record"),
"nyc" => array("whois.nic.nyc","queried object does not exist"),
"nz" => array("whois.srs.net.nz","220 Available"),
"odo.br" => array("whois.nic.br","No match for"),
"om" => array("whois.registry.om","No Data Found"),
"one" => array("whois.nic.one","No Data Found"),
"online" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"onl" => array("whois.afilias-srs.net","NOT FOUND"),
"onl" => array("whois.donuts.co","Domain not found"),
"ooo" => array("whois.nic.ooo","No match for"),
"or.ac" => array("whois.nic.ac","is not registered"),
"or.at" => array("whois.nic.at","nothing found"),
"or.id" => array("whois.pandi.or.id","DOMAIN NOT FOUND"),
"or.jp" => array("whois.nic.ad.jp","No match!!"),
"or.ke" => array("whois.kenic.or.ke","No Object Found"),
"or.kr" => array("whois.nic.or.kr","domain was not found"),
"or.kr" => array("whois.nic.or.kr","is not registered"),
"or.th" => array("whois.thnic.net","No match for"),
"or.tz" => array("whois.tznic.or.tz","No entries found"),
"org.au" => array("whois-check.ausregistry.net.au","---Available"),
"org.au" => array("whois.aunic.net","No Data Found"),
"org.br" => array("whois.nic.br","No match for"),
"org.cn" => array("whois.cnnic.net.cn","No matching record"),
"org.ec" => array("whois.lac.net","No match found"),
"org.gr" => array("http://grwhois.ics.forth.gr:800/plainwhois/plainWhois?domainName=","HTTPREQUEST-not exist"),
"org.gr" => array("http:\/\/grwhois.ics.forth.gr:800\/plainwhois\/plainWhois?domainName=","not exist"),
"org.gt" => array("http://www.gt/cgi-bin/whois.cgi?domain=","HTTPREQUEST-DOMINIO NO REGISTRADO"),
"org.gt" => array("http:\/\/www.gt\/cgi-bin\/whois.cgi?domain=","DOMINIO NO REGISTRADO"),
"org.hk" => array("whois.hkdnr.net.hk","The domain has not been registered"),
"org.il" => array("whois.isoc.org.il","No data was found"),
"org.in" => array("whois.inregistry.in","NOT FOUND"),
"org.mm" => array("whois.nic.mm","No domains matched"),
"org.mx" => array("whois.nic.mx","Object_Not_Found"),
"org.my" => array("whois.mynic.my","does not exist in database"),
"org.my" => array("whois.mynic.net.my","does not exist"),
"org.nz" => array("whois.srs.net.nz","220 Available"),
"org.pa" => array("http://www.nic.pa/whois.php?nombre_d=","HTTPREQUEST-esta disponible para ser Registrado"),
"org.ph" => array("https://whois.dot.ph/?search=","HTTPREQUEST-Domain is available"),
"org.pl" => array("whois.dns.pl","No information available"),
"org.ro" => array("whois.rotld.ro","No entries found"),
"org.rs" => array("whois.rnids.rs","%ERROR:103"),
"org.ru" => array("whois.nic.ru","No entries found"),
"org.ru" => array("whois.ripn.net","No entries found"),
"org.sg" => array("whois.nic.net.sg","Domain Not Found"),
"org.tr" => array("whois.metu.edu.tr","No match found"),
"org.tw" => array("whois.twnic.net","No Found"),
"org.ua" => array("whois.net.ua","No entries found"),
"org.uk" => array("whois.nic.uk","No match"),
"org.ve" => array("whois.nic.ve","No match for"),
"org.za" => array("http:\/\/org.za\/cgi-bin\/rwhois?format=full&domain=","Domain not registered"),
"org.za" => array("org-whois.registry.net.za","Available"),
"organic" => array("whois.afilias.net","NOT FOUND"),
"org" => array("whois.publicinterestregistry.net","NOT FOUND"),
"ovh" => array("whois-ovh.nic.fr","Requested Domain cannot be found"),
"paris" => array("whois-paris.nic.fr","Requested Domain cannot be found"),
"partners" => array("whois.donuts.co","Domain not found"),
"parts" => array("whois.donuts.co","Domain not found"),
"party" => array("whois.nic.party","object does not exist"),
"pa" => array("http://www.nic.pa/whois.php?nombre_d=","HTTPREQUEST-esta disponible para ser Registrado"),
"pc.pl" => array("whois.dns.pl","No information available"),
"pe" => array("kero.yachay.pe","Domain Status: No Object Found"),
"pf" => array("whois.registry.pf","Domain unknown"),
"photography" => array("whois.donuts.co","Domain not found"),
"photos" => array("whois.donuts.co","Domain not found"),
"photo" => array("whois.uniregistry.net","is available for"),
"physio" => array("whois.nic.physio","No Data Found"),
"ph" => array("https://whois.dot.ph/?search=","HTTPREQUEST-Domain is available"),
"pics" => array("whois.uniregistry.net","is available for"),
"pictures" => array("whois.donuts.co","Domain not found"),
"pink" => array("whois.donuts.co","Domain not found"),
"pizza" => array("whois.donuts.co","Domain not found"),
"place" => array("whois.donuts.co","Domain not found"),
"plc.uk" => array("whois.nic.uk","No match"),
"plumbing" => array("whois.donuts.co","Domain not found"),
"plus" => array("whois.donuts.co","Domain not found"),
"pl" => array("whois.dns.pl","No information available"),
"pm" => array("whois.nic.pm","No entries found"),
"pohl" => array("whois.ksregistry.net","not found..."),
"poker" => array("whois.afilias.net","NOT FOUND"),
"porn" => array("whois.afilias-srs.net","NOT FOUND"),
"post" => array("whois.dotpostregistry.net","NOT FOUND"),
"pp.ru" => array("whois.nic.ru","No entries found"),
"pp.ru" => array("whois.ripn.net","No entries found"),
"ppg.br" => array("whois.nic.br","No match for"),
"presse.fr" => array("whois.nic.fr","No entries found"),
"press" => array("whois.donuts.co","---TLD is not supported."),
"press" => array("whois.nic.press","DOMAIN NOT FOUND"),
"priv.no" => array("whois.norid.no","No match"),
"priv.pl" => array("whois.dns.pl","No information available"),
"pro.br" => array("whois.nic.br","No match for"),
"productions" => array("whois.donuts.co","Domain not found"),
"prod" => array("domain-registry-whois.l.google.com","Domain not found."),
"prof" => array("domain-registry-whois.l.google.com","Domain not found."),
"properties" => array("whois.donuts.co","Domain not found"),
"property" => array("whois.uniregistry.net","is available for"),
"pro" => array("whois.nic.pro","NOT FOUND"),
"pr" => array("whois.nic.pr","is not registered"),
"psc.br" => array("whois.nic.br","No match for"),
"psi.br" => array("whois.nic.br","No match for"),
"pt" => array("whois.dns.pt","no match"),
"pub" => array("whois.unitedtld.com","Domain not found"),
"pw" => array("whois.nic.pw","DOMAIN NOT FOUND"),
"qa" => array("whois.registry.qa","No Data Found"),
"qc.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"qh.cn" => array("whois.cnnic.net.cn","No matching record"),
"qpon" => array("whois.nic.qpon","object does not exist"),
"quebec" => array("whois.nic.quebec","no matching objects found"),
"re.kr" => array("whois.nic.or.kr","is not registered"),
"realestate.pl" => array("whois.dns.pl","No information available"),
"rec.br" => array("whois.nic.br","No match for"),
"rec.ro" => array("whois.rotld.ro","No entries found"),
"recipes" => array("whois.donuts.co","Domain not found"),
"red" => array("whois.donuts.co","Domain not found"),
"rehab" => array("whois.rightside.co","Domain not found."),
"reisen" => array("whois.donuts.co","Domain not found"),
"reise" => array("whois.nic.reise","Domain not found."),
"reit" => array("whois.nic.reit","DOMAIN NOT FOUND"),
"rel.pl" => array("whois.dns.pl","No information available"),
"rentals" => array("whois.donuts.co","Domain not found"),
"repair" => array("whois.donuts.co","Domain not found"),
"report" => array("whois.donuts.co","Domain not found"),
"republican" => array("whois.rightside.co","Domain not found."),
"res.in" => array("whois.inregistry.in","NOT FOUND"),
"restaurant" => array("whois.donuts.co","Domain not found"),
"rest" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"reviews" => array("whois.nic.reviews","Domain not found."),
"review" => array("whois.nic.review","---"),
"re" => array("whois.nic.re","No entries found"),
"rich" => array("whois.afilias-srs.net","NOT FOUND"),
"rio" => array("whois.gtlds.nic.br","No match for"),
"rip" => array("whois.rightside.co","Domain not found."),
"rocks" => array("whois.unitedtld.com","Domain not found."),
"rodeo" => array("whois-dub.mm-registry.com","is available for registration"),
"ro" => array("whois.rotld.ro","No entries found"),
"rsvp" => array("domain-registry-whois.l.google.com","Domain not found."),
"rs" => array("whois.rnids.rs","%ERROR:103"),
"ruhr" => array("whois.nic.ruhr","% no matching objects found"),
"run" => array("whois.donuts.co","Domain not found"),
"ru" => array("whois.ripn.net","No entries found"),
"sa.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"saarland" => array("whois.ksregistry.net","The queried object does not exist:"),
"sale" => array("whois.rightside.co","---Domain not found."),
"sale" => array("whois.rightside.co","Domain not found."),
"samsung" => array("whois.nic.samsung","No match for"),
"sarl" => array("whois.donuts.co","Domain not found"),
"saxo" => array("whois.aridnrs.net.au","No Data Found"),
"sa" => array("whois.nic.net.sa","No Match"),
"sb" => array("whois.nic.net.sb","Domain Status: No Object Found"),
"sc.cn" => array("whois.cnnic.net.cn","No matching record"),
"sc.ke" => array("whois.kenic.or.ke","No Object Found"),
"sc.tz" => array("whois.tznic.or.tz","No entries found"),
"sca" => array("whois.nic.sca","No match for"),
"scb" => array("whois.nic.scb","NOT FOUND"),
"sch.id" => array("whois.pandi.or.id","DOMAIN NOT FOUND"),
"schmidt" => array("whois.nic.schmidt","No Data Found"),
"school.nz" => array("whois.srs.net.nz","220 Available"),
"school.za" => array("whois.co.za","No information available"),
"school" => array("whois.donuts.co","Domain not found"),
"schule" => array("whois.donuts.co","Domain not found"),
"science" => array("whois.nic.science","object does not exist"),
"scot" => array("whois.scot.coreregistry.net","no matching objects found"),
"sc" => array("wawa.eahd.or.ug","No entries found"),
"sc" => array("whois2.afilias-grs.net","NOT FOUND"),
"se.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"se.net" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"services" => array("whois.donuts.co","Domain not found"),
"sexy" => array("whois.uniregistry.net","is available for registration"),
"se" => array("whois.iis.se","not found"),
"sg" => array("whois.nic.net.sg","Domain Not Found"),
"sh.cn" => array("whois.cnnic.net.cn","No matching record"),
"shiksha" => array("whois.nic.shiksha","NOT FOUND"),
"shoes" => array("whois.donuts.co","Domain not found"),
"shop.pl" => array("whois.dns.pl","No information available"),
"show" => array("whois.donuts.co","Domain not found"),
"sh" => array("whois.nic.sh","is available for purchase"),
"shop" => array ("whois.nic.shop", "No information available"),
"singles" => array("whois.donuts.co","Domain not found"),
"site" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"si" => array("whois.arnes.si","No entries found"),
"sklep.pl" => array("whois.dns.pl","No information available"),
"sky" => array("whois.nic.sky","No match for"),
"sk" => array("whois.sk-nic.sk","Not found"),
"slg.br" => array("whois.nic.br","No match for"),
"sm" => array("whois.nic.sm","No entries found"),
"sn.cn" => array("whois.cnnic.net.cn","No matching record"),
"sn" => array("whois.nic.sn","NOT FOUND"),
"sochi.su" => array("whois.nic.ru","No entries found"),
"social" => array("whois.nic.social","Domain not found."),
"software" => array("whois.rightside.co","Domain not found."),
"solar" => array("whois.donuts.co","Domain not found"),
"solutions" => array("whois.donuts.co","Domain not found"),
"sos.pl" => array("whois.dns.pl","No information available"),
"soy" => array("domain-registry-whois.l.google.com","Domain not found."),
"so" => array("whois.nic.so","DOMAIN NOT FOUND"),
"space" => array("whois.nic.space","DOMAIN NOT FOUND"),
"spb.ru" => array("whois.nic.ru","No entries found"),
"spiegel" => array("whois.ksregistry.net","not found..."),
"store.ro" => array("whois.rotld.ro","No entries found"),
"store" => array("whois.nic.store","NOT FOUND"),
"studio" => array("whois.rightside.co","---Domain not found."),
"study" => array("whois.nic.study","No Data Found"),
"style" => array("whois.donuts.co","Domain not found"),
"st" => array("whois.nic.st","No entries found"),
"sucks" => array("whois.nic.sucks","No Data Found"),
"supplies" => array("whois.donuts.co","Domain not found"),
"supply" => array("whois.donuts.co","Domain not found"),
"support" => array("whois.donuts.co","Domain not found"),
"surf" => array("whois-dub.mm-registry.com","is available for registration"),
"surgery" => array("whois.donuts.co","Domain not found"),
"su" => array("whois.ripn.net","No entries found"),
"sx" => array("whois.sx","Status: AVAILABLE"),
"sydney" => array("whois.nic.sydney","No Data Found"),
"systems" => array("whois.donuts.co","Domain not found"),
"sy" => array("whois.tld.sy","Available"),
"taipei" => array("whois.nic.taipei","Not found:"),
"targi.pl" => array("whois.dns.pl","No information available"),
"tatar" => array("whois.nic.tatar","No entries found"),
"tattoo" => array("whois.uniregistry.net","is available for registration"),
"tax" => array("whois.donuts.co","Domain not found"),
"tc" => array("whois.adamsnames.tc","No Object Found"),
"team" => array("whois.donuts.co","Domain not found"),
"technology" => array("whois.donuts.co","Domain not found"),
"tech" => array("whois.nic.tech","DOMAIN NOT FOUND"),
"tel" => array("whois.nic.tel","Not found"),
"tennis" => array("whois.donuts.co","Domain not found"),
"tf" => array("whois.nic.tf","No entries found"),
"th" => array("whois.thnic.co.th","No match for"),
"tienda" => array("whois.donuts.co","Domain not found"),
"tienda" => array("whois.nic.tienda","Domain not found."),
"tips" => array("whois.donuts.co","Domain not found"),
"tires" => array("whois.donuts.co","Domain not found"),
"tirol" => array("whois.nic.tirol","% No match"),
"tj.cn" => array("whois.cnnic.net.cn","No matching record"),
"tj" => array("whois.nic.tj","No match"),
"tk" => array("whois.dot.tk","Invalid query or domain name not known in Dot TK Domain Registry"),
"tl" => array("whois.nic.tl","Domain Status: No Object Found"),
"tm.fr" => array("whois.nic.fr","No entries found"),
"tm.mc" => array("whois.ripe.net","no entries found"),
"tm.pl" => array("whois.dns.pl","No information available"),
"tm.ro" => array("whois.rotld.ro","No entries found"),
"tm.za" => array("whois.co.za","No information available"),
"tmp.br" => array("whois.nic.br","No match for"),
"tm" => array("whois.nic.tm","is available"),
"tn" => array("whois.ati.tn","NO OBJECT FOUND!"),
"today" => array("whois.donuts.co","Domain not found"),
"tools" => array("whois.donuts.co","Domain not found"),
"top" => array("whois.nic.top","queried object does not exist"),
"toshiba" => array("whois.nic.toshiba","DOMAIN NOT FOUND"),
"tourism.pl" => array("whois.dns.pl","No information available"),
"tours" => array("whois.donuts.co","Domain not found"),
"town" => array("whois.donuts.co","Domain not found"),
"toys" => array("whois.donuts.co","Domain not found"),
"to" => array("monarch.tonic.to","No match for"),
"trade" => array("whois.nic.trade","queried object does not exist"),
"training" => array("whois.donuts.co","Domain not found"),
"travel.pl" => array("whois.dns.pl","No information available"),
"travel" => array("whois.nic.travel","Not found"),
"trust" => array("whois.nic.trust","No Data Found"),
"tt" => array("https:\/\/www.nic.tt\/cgi-bin\/search.pl?name=","is available"),
"tui" => array("whois.ksregistry.net","not found..."),
"tur.br" => array("whois.nic.br","No match for"),
"turystyka.pl" => array("whois.dns.pl","No information available"),
"tv.br" => array("whois.nic.br","No match for"),
"tv.tz" => array("whois.tznic.or.tz","No entries found"),
"tv" => array("whois.nic.tv","No match for"),
"tw.cn" => array("whois.cnnic.net.cn","No matching record"),
"tw" => array("whois.twnic.net.tw","No Found"),
"tz" => array("whois.tznic.or.tz","% No entries found."),
"ua" => array("whois.ua","No entries found"),
"ug" => array("whois.co.ug","% No entries found."),
"uk.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"uk.co" => array("whois.uk.co","NO MATCH"),
"uk.net" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"uk" => array("whois.nic.uk","No match"),
"uk" => array("whois.nic.uk","This domain name has not been registered."),
"university" => array("whois.donuts.co","Domain not found"),
"university" => array("whois.nic.university","Domain not found"),
"uno" => array("whois.afilias.net","Not found"),
"uno" => array("whois.nic.uno","Not found"),
"uol" => array("whois.gtlds.nic.br","No match for"),
"us.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"us" => array("whois.nic.us","Not found"),
"uy.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"uy" => array("whois.nic.org.uy","No match for"),
"uz" => array("whois.cctld.uz","not found..."),
"vacations" => array("whois.donuts.co","Domain not found"),
"vc" => array("whois.adamsnames.tc","Available"),
"vegas" => array("whois.afilias-srs.net","NOT FOUND"),
"ventures" => array("whois.donuts.co","Domain not found"),
"versicherung" => array("whois.nic.versicherung","% No match"),
"vet.br" => array("whois.nic.br","No match for"),
"vet" => array("whois.rightside.co","Domain not found."),
"ve" => array("whois.nic.ve","No match for"),
"vg" => array("whois.nic.vg","not found..."),
"viajes" => array("whois.donuts.co","Domain not found"),
"video" => array("whois.rightside.co","Domain not found."),
"villas" => array("whois.donuts.co","Domain not found"),
"vision" => array("whois.donuts.co","Domain not found"),
"vlaanderen" => array("whois.nic.vlaanderen","is still available"),
"vodka" => array("whois-dub.mm-registry.com","is available for registration"),
"vote" => array("whois.afilias.net","NOT FOUND"),
"voting" => array("whois.voting.tld-box.at","% No match"),
"voto" => array("whois.afilias.net","NOT FOUND"),
"voyage" => array("whois.donuts.co","Domain not found"),
"vu" => array("vunic.vu","is not valid!"),
"wales" => array("whois.nic.wales","This domain name has not been registered."),
"wang" => array("whois.gtld.knet.cn","No match"),
"watch" => array("whois.donuts.co","Domain not found"),
"web.id" => array("whois.pandi.or.id","DOMAIN NOT FOUND"),
"web.ve" => array("whois.nic.ve","No match for"),
"web.za" => array("web-whois.registry.net.za","Available"),
"webcam" => array("whois.nic.webcam","object does not exist"),
"website" => array("whois.nic.website","DOMAIN NOT FOUND"),
"wedding" => array("whois-dub.mm-registry.com","---"),
"wedding" => array("whois-dub.mm-registry.com","is available for registration"),
"wed" => array("whois.nic.wed","Domain Status: No Object Found"),
"wf" => array("whois.nic.wf","No entries found"),
"whoswho" => array("whois.nic.whoswho","Not found:"),
"wien" => array("whois.nic.wien","% No match"),
"wiki" => array("whois.donuts.co","Domain not found"),
"wme" => array("whois.nic.wme","DOMAIN NOT FOUND"),
"works" => array("whois.donuts.co","Domain not found"),
"work" => array("whois-dub.mm-registry.com","Not Registered"),
"work" => array("whois-dub.mm-registry.com","is available for registration"),
"work" => array("whois.nic.work","queried object does not exist"),
"world" => array("whois.donuts.co","Domain not found"),
"ws" => array("whois.website.ws","No match for"),
"wtc" => array("whois.nic.wtc","No Data Found"),
"wtf" => array("whois.donuts.co","Domain not found"),
"www.ro" => array("whois.rotld.ro","No entries found"),
"xj.cn" => array("whois.cnnic.net.cn","No matching record"),
"xn--1qqw23a" => array("whois.ngtld.cn","No match"),
"xn--3bst00m" => array("whois.gtld.knet.cn","No match"),
"xn--3ds443g" => array("whois.afilias-srs.net","NOT FOUND"),
"xn--3e0b707e" => array("whois.kr","Above domain name is not registered to"),
"xn--45q11c" => array("whois.nic.xn--45q11c","No match"),
"xn--4gbrim" => array("whois.afilias-srs.net","NOT FOUND"),
"xn--55qw42g" => array("whois.conac.cn","Not find MatchingRecord"),
"xn--55qx5d" => array("whois.ngtld.cn","No match"),
"xn--6frz82g" => array("whois.afilias.net","NOT FOUND"),
"xn--6qq986b3xl" => array("whois.gtld.knet.cn","No match"),
"xn--80adxhks" => array("whois.nic.xn--80adxhks","No entries found"),
"xn--80ao21a" => array("whois.nic.kz","Nothing found for this query."),
"xn--80asehdb" => array("whois.online.rs.corenic.net","% no matching objects found"),
"xn--80aswg" => array("whois.site.rs.corenic.net","% no matching objects found"),
"xn--c1avg" => array("whois.publicinterestregistry.net","NOT FOUND"),
"xn--clchc0ea0b2g2a9gcd" => array("whois.sgnic.sg","Domain Not Found"),
"xn--czrs0t" => array("whois.donuts.co","Domain not found"),
"xn--czru2d" => array("whois.gtld.knet.cn","No match"),
"xn--d1acj3b" => array("whois.nic.xn--d1acj3b","No entries found"),
"xn--d1alf" => array("whois.marnet.mk","% No entries found."),
"xn--fiq228c5hs" => array("whois.afilias-srs.net","NOT FOUND"),
"xn--fiq64b" => array("whois.gtld.knet.cn","No match"),
"xn--fiqs8s" => array("cwhois.cnnic.cn","no matching record"),
"xn--fiqz9s" => array("cwhois.cnnic.cn","no matching record"),
"xn--flw351e" => array("domain-registry-whois.l.google.com","Domain not found."),
"xn--hxt814e" => array("whois.nic.xn--hxt814e","No match"),
"xn--i1b6b1a6a2e" => array("whois.publicinterestregistry.net","NOT FOUND"),
"xn--io0a7i" => array("whois.ngtld.cn","No match"),
"xn--j1amh" => array("whois.dotukr.com","No match for"),
"xn--j6w193g" => array("whois.hkirc.hk","The domain has not been registered"),
"xn--kput3i" => array("whois.afilias-srs.net","NOT FOUND"),
"xn--lgbbat1ad8j" => array("whois.nic.dz","NO OBJECT FOUND!"),
"xn--mgb9awbf" => array("whois.registry.om","No Data Found"),
"xn--mgba3a4f16a" => array("whois.nic.ir","% No entries found."),
"xn--mgbaam7a8h" => array("whois.aeda.net.ae","No Data Found"),
"xn--mgberp4a5d4ar" => array("whois.nic.net.sa","No Match"),
"xn--mgbx4cd0ab" => array("whois.mynic.my","does not exist in database"),
"xn--mxtq1m" => array("whois.nic.xn--mxtq1m","Not Found."),
"xn--ngbc5azd" => array("whois.nic.xn--ngbc5azd","No Data Found"),
"xn--nqv7f" => array("whois.publicinterestregistry.net","NOT FOUND"),
"xn--o3cw4h" => array("whois.thnic.co.th","No match for"),
"xn--ogbpf8fl" => array("whois.tld.sy","Available"),
"xn--p1acf" => array("whois.nic.xn--p1acf","Domain Status: No Object Found"),
"xn--p1ai" => array("whois.ripn.net","No entries found"),
"xn--q9jyb4c" => array("domain-registry-whois.l.google.com","Domain not found."),
"xn--qcka1pmc" => array("domain-registry-whois.l.google.com","Domain not found."),
"xn--unup4y" => array("whois.donuts.co","Domain not found"),
"xn--vermgensberater-ctb" => array("whois.ksregistry.net","not found..."),
"xn--vermgensberatung-pwb" => array("whois.ksregistry.net","not found..."),
"xn--vhquv" => array("whois.donuts.co","Domain not found"),
"xn--wgbl6a" => array("whois.registry.qa","No Data Found"),
"xn--xhq521b" => array("whois.ngtld.cn","No match"),
"xn--yfro4i67o" => array("whois.sgnic.sg","Domain Not Found"),
"xn--ygbi2ammx" => array("whois.pnina.ps","Available"),
"xn--zfr164b" => array("whois.conac.cn","Not find MatchingRecord"),
"xxx" => array("whois.nic.xxx","NOT FOUND"),
"xyz" => array("whois.nic.xyz","DOMAIN NOT FOUND"),
"xz.cn" => array("whois.cnnic.net.cn","No matching record"),
"yn.cn" => array("whois.cnnic.net.cn","No matching record"),
"yodobashi" => array("whois.nic.gmo","DOMAIN NOT FOUND"),
"yoga" => array("whois.nic.yoga","queried object does not exist"),
"youtube" => array("domain-registry-whois.l.google.com","Domain not found."),
"yt" => array("whois.nic.yt","No entries found"),
"za.com" => array("whois.centralnic.com","DOMAIN NOT FOUND"),
"zip" => array("domain-registry-whois.l.google.com","Domain not found."),
"zj.cn" => array("whois.cnnic.net.cn","No matching record"),
"zlg.br" => array("whois.nic.br","No match for"),
"zm" => array("whois.nic.zm","Domain Status: No Object Found"),
"zone" => array("whois.donuts.co","Domain not found"),
"zuerich" => array("whois.ksregistry.net","not found..."),
"gmbh" => array("whois.donuts.co", "Domain not found"),
"vlaanderen" => array("whois.nic.vlaanderen","The queried object does not exist"),
"brussels" => array("whois.nic.brussels","The queried object does not exist"),
"be" => array("whois.dns.be", "Status:	AVAILABLE"),
"com.ar" => array("whois.nic.ar", "No entries found.")
		);

	
		// gethostbyname returns the same string if it cant find the domain,
		// we do a further check to see if it is a false positive
		//if (gethostbyname($domain) == $domain) {
			// get the TLD of the domain
			$tld = $this->get_tld($domain);
			
			// If an entry for the TLD exists in the whois array
			if (isset($whois_arr[$tld][0])) {
				// set the hostname for the whois server
				$whois_server = $whois_arr[$tld][0];

				// set the "domain not found" string
				$bad_string = $whois_arr[$tld][1];
			} else {
				// TODO: REFACTOR THIS
				// TLD is not in the whois array, die
				//throw new Exception("WHOIS server not found for that TLD");

				//return 'not found';
    			return json_encode(array('status'=>2));


			}

			$status = $this->checkDomainNameAvailabilty($domain,$whois_server,$bad_string,null);
			
			return $status;
		//} else {
			// not available
		//	return FALSE;
		//}

}
	

	/**
	 * Extracts the TLD from a domain, supports URLS with "www." at the beginning.
	 *
	 * @author  Helge Sverre <email@helgesverre.com>
	 *
	 * @param string $domain The domain that will get it's TLD extracted
	 * @return string The TLD for $domain
	 */

	public function get_tld ($domain) {
		$split = explode('.', $domain,2);

		if(count($split) === 0) {
			//throw new Exception('Invalid domain extension');
			return false;
		}
		//return end($split);
		$tld = strtolower(array_pop($split));
		return $tld;

	}

	public function checkDomainNameAvailabilty($domain_name, $whois_server, $find_text){
    // Open a socket connection to the whois server

    list($dom, $ext) = explode('.', $domain_name, 2);
		
    $con = fsockopen($whois_server, 43, $errno, $errstr, 3);
    if (!$con) return file__get_contents("http://api.asdqwe.net/api/whois.php?d=$domain_name");
 
    // Send the requested domain name
    fputs($con, $domain_name."\r\n");
 
    // Read and store the server response
    $response = " :";
    while(!feof($con))
        $response .= fgets($con,128); 
 
    // Close the connection
    fclose($con);
 
    // Check the Whois server response
    if (strpos($response, $find_text))
	//return 'true';
    	return json_encode(array('status'=>1));
    else
    //return 'false';
    	return json_encode(array('status'=>0));
	}
}

